import { Inter } from 'next/font/google'

import { CustomFooter, CustomNavbar } from '../import'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Car Catalog',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className='relative'>
				<CustomNavbar />
				<main>{children}</main>
				<CustomFooter />
			</body>
		</html>
	)
}
